### PR TITLE
Removed Unnecessary Created() from CollectionBrowseMixin file

### LINKED ISSUE #721: Unnecessarily calling a method in created()
## Describe the bug
Unnecessarily calling a method in created and watch. The thought behind this is we want to run the watch hook as soon as a component is initialized.

## Expected behavior
But Vue has a built-in solution for this. It’s a property of Vue watchers that we often forget.
All we have to do is restructure our watcher a little bit and declare two properties:
1)  handler (newVal, oldVal) — this is our watcher method itself.
2)  immediate: true — this makes our handler run when our instance is created.

## Screenshots

created

## Desktop (please complete the following information)
 - OS: Ubuntu

## Additional context
Want to work on this :)

### PR DESCRIPTION
**Pull request by abhisheknaiidu**
Fixes #721 

Modified Code-base

Developer Certificate of Origin Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors. 1 Letterman Drive Suite D4700 San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

### CODE REVIEW

**Comment by abhisheknaiidu** [comment]
@akmadian Could you review this once?

**Comment by akmadian** [comment]
@abhisheknaiidu Still waiting on @brenoferreira, please ping me if we don't get a response in a couple days and I'll PM him

**Comment by abhisheknaiidu** [comment]
@akmadian ohkk :)

**Comment by akmadian** [comment]
I'll let @brenoferreira review this it seems like the broken behaviors could extend relatively deeply, and I don't know exactly what to test, and how I would test those things.

**Comment by brenoferreira** [comment]
This created handler is called during SSR, so I don't think this change will work for us

Thanks for your contribution.

**Pull request closed without merging**
