### PR TITLE
Added a/b test for language on Donation banner

### LINKED ISSUE #1233: A/B test language on donation banner
Suggestions welcome in the comments.

Something like:
"Only X% of people reading this will donate. Be one of them and help us sustain CC Search."

Look at our stats to glean what the X% is since launching just under a week ago.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #1233 by @annatuma 

## Description

Add a/b test for donation banner language. Currently the banner says "If you donate $5 today, and everyone else does the same, we can keep growing our database of freely reusable content. For you. For all of us.". The test version is "Only 1% of people reading this will donate. Be one of them and help us sustain CC Search."

## Technical details

Previously, a/b tests were initialized in the `clientEntry.js`. After the Nuxt migration, we no longer have `clientEntry.js`. I added initialization of a/b tests to the `index.vue` page. If there's a better place for it, I will fix it.

The ab experiments are added to store asynchronously, so when the page loads, the store doesn't have experiments in it. This is why I watch the store for mutations to a/b experiment data, and update the donation text when it loads.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — CHANGES_REQUESTED** [review]
**Edit: the below is a great idea, but we currently use server microcaching so shouldn't have any app state server-side. Maybe in the future we can re-visit this.**

Hi @obulat your code and the way you did it is perfect. However, I think we can make an improvement (that we didn't have _before Nuxt_ even). We can try to load the a/b tests server-side so that the test contents don't flash on the client-side and you don't need to watch the store for the a/b test promises to be done. 

I think we can do this in the main store file, in Nuxt's `nuxtServerInit` action:

https://github.com/creativecommons/cccatalog-frontend/blob/4f4367a4c0e8e763f2d2d7e7135188735fae0d20/src/store/index.js#L26

I have pushed one commit of annotating that file with a jsdoc block, and showing how you can read cookies server-side with `res.headers.cookies`, which returns this (example): `abSessionId=1870427f-7891-4c30-ac4f-785f8344e8bb; usageSessionId=2923e85b-7312-4c87-a464-d25ea471847b; _ga=GA1.1.594780576.1601855376; SESSION_ID=2df84a91-8fb8-4df6-8b55-86c78573b513`.

I think you'll be able to figure out the rest, will probably need to do a little refactoring to set/get the ab test cookie server-side.

**Comment by zackkrida** [comment]
@obulat This is great. Last thing, the a/b test needs to _convert_ when the donate button is clicked. This is how we determine which language is more effective. You can see an example of the dispatch for a na/b conversion here https://github.com/creativecommons/cccatalog-frontend/blob/fd4bdb7297cc1ba81c56aa2d21b6e4062e1acfbf/src/store/abtest-store.js and here https://github.com/creativecommons/cccatalog-frontend/blob/fd4bdb7297cc1ba81c56aa2d21b6e4062e1acfbf/src/store/filter-store.js#L96

**Review by zackkrida — CHANGES_REQUESTED** [review]
see comments above!

**Comment by obulat** [comment]
I added the conversion, and also changed keyboard event handling a little bit: 

@click event on a button automatically handles the keyboard <kbd>Enter</kbd> and <kbd>space</kbd> presses as well. Or, to be more precise, pressing <kbd>Enter</kbd> or <kbd>space</kbd> when a button is focused triggers a 'click' event, which is handled by the @click handler. This is why I removed the keypress handling.
The 'vue-a11y' plugin shows this as an error, however there's [an issue about this](https://github.com/maranran/eslint-plugin-vue-a11y/issues/10) . It seems that the plugin development has stopped 17 months ago, and there is an alternative plugin ([eslint-plugin-vuejs-accessibility](https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility)) worth considering.

Because our 'Donate' button is actually an `a` link element, its 'click' event is also triggered when user presses <kbd>Enter</kbd> key when it is focused. This is why I removed onkeypress handler. However, a link does not handle pressing <kbd>space</kbd> natively or using vue directives.

**Review by zackkrida — APPROVED** [review]
🥳 _Thank you_ for addressing the a11y keypress + click issues. I was aware of the problem but forgot to make a ticket for it. Your suggestion is great.

**Pull request merged**
