### PR TITLE
Test Coverage scripts for pages/client

### LINKED ISSUE #232: Improve test coverage for components
Write unit tests for the [components](https://github.com/creativecommons/cccatalog-frontend/tree/master/src/components) and [pages](https://github.com/creativecommons/cccatalog-frontend/tree/master/src/pages).

There are already [some components with unit tests](https://github.com/creativecommons/cccatalog-frontend/blob/master/test/unit/specs/components/photo-details.spec.js), please use them as guidelines for writing future tests

### PR DESCRIPTION
**Pull request by AyanChoudhary**
Fixes #232 

Tests for client page: Browsepage, CollectionBrowsePage, PhotoDetailPage

---

Developer Certificate of Origin Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors. 1 Letterman Drive Suite D4700 San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

### CODE REVIEW

**Comment by AyanChoudhary** [comment]
The test which is failing is due to PhotoDetailPage which uses the featureflags file to get status of watermark and socialsharing flags from the env, which will have to be setup in the build

**Comment by AyanChoudhary** [comment]
This PR is ready for review.

**Comment by akmadian** [comment]
While we're waiting for Breno's review, please try to find a way to mock the status of watermark and socialsharing flags. We can't commit tests that always fail.

**Comment by AyanChoudhary** [comment]
I have fixed the tests with a passing build as mentioned in the other pr. #635

**Pull request merged**
