### PR TITLE
Fix incorrect bottom-padding spacing in content section 

### LINKED ISSUE #953: The bottom-padding spacing in content section is incorrect
## Describe the bug
The spacing used as bottom-padding in the section where the image is presented is incorrect.

## Expected behavior
The spacing should be 64px, as defined in [the mockup (Mockup S3)](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=199%3A354&viewport=4014%2C2158%2C0.5814259648323059).

## Screenshots
Screen Shot 2020-05-14 at 12 19 41

### PR DESCRIPTION
**Pull request by ariessa**
## Fixes

Fixes #953 by @panchovm 

## Description
Added class padding-bottom-small to content section

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `master` branch of the repository.
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [X] I added tests for the changes I made (if applicable).
- [X] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by brenoferreira** [comment]
The problem with this fixed 64px padding is that the size of this area depends a lot on the image resolution. With this 64px padding, some cases end up with too much empty space.
Screen Shot 2020-05-22 at 11 00 28

I think a `padding-bottom-normal` (16px) works best for most cases (big and small images)

Screen Shot 2020-05-22 at 11 03 44
Screen Shot 2020-05-22 at 11 03 29
@panchovm

**Comment by panchovm** [comment]
Oh yes yes. I am aware of that situation. That's why I reviewed it with a full-width image, just to see how padding/margin was applied.

**Comment by zackkrida** [comment]
Hi @panchovm I wanted to follow-up with you here. Do you think the `64px` of padding recommended by this PR is acceptable or too tall? I couldn't tell what you and Breno decided.

**Comment by panchovm** [comment]
I still believe that 64px is reasonable to separate the image's information from the tag and related images section (see [this reference](https://d.pr/free/i/7DzW22)). That is the first point of this request. But I do agree that it should depend on which section is taller.

**Pull request merged**
