### PR TITLE
Issue #856 Overlap links in Homepage

### LINKED ISSUE #856: help links on homepage overlaps on medium screen
## Describe the bug
The line contains two links on the left side of check-boxes are overlapping with the check-boxes on 
the medium screens.

## To Reproduce

1. Go to [homepage](https://ccsearch.creativecommons.org/)
2. resize the window 
3. take a close look on the line beside the check-boxes

## Expected behavior
The following should happen

- on medium screen the line should not overlap with the check-boxes

- or should come below the check-boxes

## Screenshots

cc-issue-1

## Desktop (please complete the following information)
 - OS: Microsoft Windows 10 pro Education
 - Browser: chrome
 - Version: Version 80.0.3987.149 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by devRD**
Fixes #856 by @Abbas-000

## Description
HeroSection.vue: Added a wrapper for help-links and modified style classes
FooterSection.vue: Added a margin to the footer top

## Screenshots

Screenshot from 2020-04-11 13-02-53

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by techievivek** [comment]
@devRD Can you try adding the following style to `help-links` class
```css
bottom: 1.5rem;
left: auto;
```
This will possibly help us reach the desired solution without much code change.
Below is a screenshot after we apply those styles.
( `left:auto` is optional, I have added to center align. )
Screenshot-20200416222228-816x188

**Comment by devRD** [comment]
@techievivek Yeah, sure I'll do the necessary changes and update the patch.

**Comment by techievivek** [comment]
@devRD I am not sure if that's the correct way, you can try it and ask for a review.

**Comment by devRD** [comment]
@techievivek I tried the solution you suggested by adding the styles to the `help-links` class. It gets properly aligned in the center in large screen width, but breaks in the medium screen, as you can see in the picture below. I tried a few iterations of it and it looks like adding proper margin classes keeps the sections separate as was the issue. 

Screenshot from 2020-04-16 22-42-25

**Comment by techievivek** [comment]
@devRD Have you tried giving `0rem` so that it sticks below? rather than floating up.

**Comment by devRD** [comment]
@techievivek Yes, I have tried the values, though they work fine on a normal window, on the medium window they tend to break and anything above `0rem` would overlap with the text as shown in the screenshot below. 

Screenshot from 2020-04-16 23-53-52

However, changing the `position` style to `relative` works with the same styles with a small addition of a margin class in the footer as shown. 

Screenshot from 2020-04-17 00-00-50

I'm not sure if the `help-link` tags require to be center-aligned. If that's the case, I would update the patch as necessary.

**Comment by techievivek** [comment]
@devRD Yeah, now it looks good. I too am not sure whether it has to be center-aligned, you can ask from mentors.

**Comment by devRD** [comment]
@akmadian @brenoferreira could you please review it once? :)

**Comment by brenoferreira** [comment]
This was fixed in #890
Thanks for your contribution.

**Pull request closed without merging**
