### PR TITLE
Updated the filter side bar on Results Page

### LINKED ISSUE #845: Updates to Results Page
We want to make some changes to the Results page in CC Search.

These changes apply only to the Filter side bar on the Results page. 

Reference the following screens in Figma when going through the list, to understand what these changes entail:
Results commercially
Results modify
Results license (for modal)
License Filter update

See mockups in [Figma](https://www.figma.com/file/0tnxdVJPRUhDJCN0LO8P5d/Mockup---Sprint-2?node-id=0%3A286).

These are the changes we want to implement:

- [x] Move the expand/collapse filter icon into the Filter side bar when expanded. (It is currently to the right of the side bar, in line with the search bar). (Complete: https://github.com/creativecommons/cccatalog-frontend/pull/867)

- [x] Add title to Filter side bar: “Filter results by”. (Complete: https://github.com/creativecommons/cccatalog-frontend/pull/867)

- [ ] Allow users to filter by both Use and License
- [ ] -- If “Use commercially” is checked, NC licenses should not be available for selection from License filter.
- [ ] -- If “Modify or adapt” is checked, ND licenses should not be available for selection from License filter.

This was being addressed in https://github.com/creativecommons/cccatalog-frontend/pull/867 but there was a misunderstanding regarding the proposed functionality.

- [x] Update the License filter, to include the License icons, as well as the License abbreviation, for example as shown in the “License Filter update” screen. (Done: https://github.com/creativecommons/cccatalog-frontend/pull/989)

- [x] Add question mark icon to each license, with modal on hover, which shows bullets per license, styled as indicated in “Results license” screen. (Done: https://github.com/creativecommons/cccatalog-frontend/pull/989 but there are some styling issues, which will be dealt with separately: https://github.com/creativecommons/cccatalog-frontend/issues/1047)

- [x] Add visual indicators to Aspect Ratio filter, for tall, wide, square, as shown in mockup. (Done: https://github.com/creativecommons/cccatalog-frontend/pull/989)

Please note that we do not want to change the background color of the Filter side bar, that should remain as it currently is.

### PR DESCRIPTION
**Pull request by abhisheknaiidu**
Related to #845  by @annatuma 

## Description
1) Updated the License filter, to include the License icons
2) Added question SVG.
3) Added visual indicators to Aspect Ratio filter, for tall, wide, square, as shown in the mockup.

   Other improvements will be done by @krysal 

## Screenshots

**License Section:**

license

**Aspect Ratio:**

aspect

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by krysal** [comment]
Hi @abhisheknaiidu, the question mark icon should also have a modal on hover, which shows bullets per license, styled as shown in the [Figma mockup](https://www.figma.com/file/0tnxdVJPRUhDJCN0LO8P5d/Mockup---Sprint-2?node-id=0%3A1180).

And since the PR just partially address the issue you should replace 'Fixes' with 'Related to'.

**Comment by abhisheknaiidu** [comment]
Oh ohk I think I just missed that part , will try to fix that, is that a tooltip, we have to add ? @krysal

**Comment by krysal** [comment]
Yes, it looks more like a tooltip.

**Comment by abhisheknaiidu** [comment]
@annatuma , @kgodey @brenoferreira Could you once review this :)

**Comment by annatuma** [comment]
Thanks for working on this @abhisheknaiidu 

Some stylistic changes, for each of the items:

**Update the License filter, to include the License icons, as well as the License abbreviation, for example as shown in the “License Filter update” screen.**

Here is a screenshot of what this should look like, more fully fleshed out than the mockup we referenced previously:
license filter - update

Left align two columns, so that icons are all left aligned, and the license abbreviations are all left aligned.

**Add question mark icon to each license, with modal on hover, which shows bullets per license, styled as indicated in “Results license” screen.**

We use icons from Font Awesome. The question mark will be added to the design library. For now, make use of this icon:
https://fontawesome.com/icons/question-circle?style=regular

The styling of the modal is not as indicated in the mockup. It includes the license name, license icons, sentence describing each icon, and a link to the license. It should match the style in the mockup exactly.

This is what the modals should be styled like:
license tooltip

Here is a Google Doc with all of the content for each tooltip, listed by license:
https://docs.google.com/document/d/12mfwy1fvWUYJhs1gKHyAoC1GVoqO0iEj6NP4uBA-SsU/edit?usp=sharing

**Add visual indicators to Aspect Ratio filter, for tall, wide, square, as shown in mockup.**

These should be center aligned, like the mockup, see screenshot:
aspect ratio

Let me know when these changes are in and paste new screenshots, and I will review again.

**Comment by abhisheknaiidu** [comment]
@annatuma I have made the following changes 

`1. Updated the License filter and added font-awesome SVG`

license

`2 Made the visual indicators aligned center`

aspect

**For adding Modal, I am not able to get what to do exactly, is it we have to add draggable one?**
because modal seems to have an effect on total page.

**Comment by annatuma** [comment]
@abhisheknaiidu when a user hovers over the question mark icon for each license, that's when the modal should show, explaining the license conditions.

It should not be draggable, and it should have icons plus text, in order to allow for translation in the future.

Does this make sense?

**Comment by abhisheknaiidu** [comment]
@annatuma Yess, it makes sense, but instead of hover it's better to add on-click function, it will be better for accessibility also.

**I made these changes** 

lice1


lice2

and I disabled this modal for all small devices because it does makes sense, and also there will be new filter form being attached to all small and smaller devices in the issue #684  
and its corresponding PR #866

**Comment by abhisheknaiidu** [comment]
@annatuma  the reason I made the size of modal little bit, different because I made just one modal for all the licenses and just passing their information dynamically through it. I guess, it's fine, right ?

**Comment by brenoferreira** [comment]
There will be some discussions about this on our upcoming internal design meeting so we'll get back to you on this next week

**Comment by brenoferreira** [comment]
This was done in #989 

Thanks for your contribution.

**Pull request closed without merging**
