### PR TITLE
modal accessibility with trap focus

### LINKED ISSUE #1052: Modal Accessibility Issues
Our [modal component](https://github.com/creativecommons/cccatalog-frontend/blob/develop/src/components/Filters/SearchGridFilter.vue#L4-L20) and our ["arrow popup" component (usage 1)](https://github.com/creativecommons/cccatalog-frontend/blob/develop/src/components/SafeBrowsing.vue#L12-L37) and [usage 2](https://github.com/creativecommons/cccatalog-frontend/blob/develop/src/components/ContentReport/ContentReportForm.vue#L2-L87) have major accessibility issues and should be extracted into their own components. They should later be moved into vue-vocabulary as well.

This is a _react component_, but the rendered HTML is an excellent reference for what features an accessible modal should support: https://reach.tech/dialog/

- [x] Extract `Modal.vue` component
- [ ] Fix a11y:
    - [ ] Add attributes `aria-modal="true" role="dialog"`
    - [ ] `esc` key closes the modal 
    - [ ] Click on the modal backdrop (the darkened area behind the modal window) closes the modal
    - [ ] Trap focus within the modal

I have actually implemented all of this on a previous open-source vue project, which could be a god reference: https://github.com/sdras/cssgridgenerator/pull/9

### PR DESCRIPTION
**Pull request by AyanChoudhary**
## Fixes

Fixes #1052 by @zackkrida 

## Description

Improves accessibility for modals.

## Technical details

Implements trap-focus and addresses some modal buggy behaviors.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
Hi @AyanChoudhary I fixed the bug with the modal re-opening after using the close button! 
HTML `<button>`s do not need explicit enter keypress events, they can cause double submits and weird behavior.

**Comment by zackkrida** [comment]
@AyanChoudhary can you re-review this in the next week? Thanks!

**Comment by AyanChoudhary** [comment]
Ah! Sure I will. 👍

**Comment by AyanChoudhary** [comment]
@zackkrida I have shifted the relevant code to another PR since we have a lot of overlapping code in this branch.

**Pull request closed without merging**
