### PR TITLE
Migrate from webpack-3 to webpack-4 and simplify webpack config files

### LINKED ISSUE #485: Simplify Webpack configuration
Currently, Webpack configs are a bit confusing and spread across [too many files](https://github.com/creativecommons/cccatalog-frontend/tree/develop/build) and even [different directories](https://github.com/creativecommons/cccatalog-frontend/tree/develop/config).

It would be nice to have just four files:

- webpack-base.js
- webpack-dev.js
- webpack-prod.js
- webpack-server.js

### PR DESCRIPTION
**Pull request by AyanChoudhary**
Fixes #485 and #548 

This PR migrates the ccc-frontend vue build from webpack-3 to webpack-4 and also simplifies the webpack config file to only 4 files: webpack-base.js, webpack-dev.js, webpack-prod.js and webpack-server.js

---

Developer Certificate of Origin Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors. 1 Letterman Drive Suite D4700 San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

### CODE REVIEW

**Comment by coderbabu10** [comment]
@AyanChoudhary i think you should not change the `.json` files,that's why the checks are getting failed

**Comment by AyanChoudhary** [comment]
> @AyanChoudhary i think you should not change the `.json` files,that's why the checks are getting failed

@coderbabu10 Actually these will be failing for a while as I am migrating the configs in phases for webpack 4. Thank You by the way :)

**Comment by akmadian** [comment]
Go ahead and ping me on this issue when you're ready for a final review :)

**Comment by AyanChoudhary** [comment]
@akmadian I have migrated the webpack configs.

**Comment by AyanChoudhary** [comment]
It looks like I missed this. Will try and fix this quickly.

**Comment by AyanChoudhary** [comment]
@akmadian I have probed into the issue and it looks like the components are not rendering(which is also causing the tooltip error). I tried fixing it which led me to try a couple of things such as fixing the minicssextractplugin errors on version change(downgrading it to be exact) but this did not solve the issue. It would be great if you could help me with this.

**Comment by akmadian** [comment]
@AyanChoudhary Please be more specific about exactly what problems you're facing, what is the error? Are components rendering? Is there anything in the browser console?

**Comment by AyanChoudhary** [comment]
> @AyanChoudhary Please be more specific about exactly what problems you're facing, what is the error? Are components rendering? Is there anything in the browser console?

The main poblem which I am facing is that the components are not rendering. The responsible plugin is minicssextractplugin which was showing a module not found even though it existed. So I d reverted back to the default loaders which work fine for the production build but not for the development server. On probing further I found that this problem occurs in several cases and is somehow related to a path mismatch, which I am not related to figure out.

**Comment by akmadian** [comment]
@AyanChoudhary Ah I see, please provide more details on the path mismatch issue so I can help you figure it out :) If by "not related to figure out" you mean that the path mismatch isn't related to the webpack migration, I would say that it is relevant to the migration, and it should be addressed in this PR.

**Comment by AyanChoudhary** [comment]
@akmadian I have resolved the path mismatch issue, it looks like it required a fallback path for the mini-css bundle, but the components are still not rendering. I am attaching the console screenshot below.
Screenshot from 2020-03-16 15-31-53

**Comment by AyanChoudhary** [comment]
I went through the component rendering and have found out the following:
 <ul>
<li> All the files are being properly parsed.
<li> The js in question is also executing
<li> The problems seems to be with the websocket connection which is causing failure on serving the components.
<li> The test which is failing is of the tooltip when it is triggered. And since the tooltip is not being rendered the wrapper is empty which fails on running the trigger function.
</ul>

I am also looking on how to fix this web socket problem for now. @akmadian

**Comment by brenoferreira** [comment]
This was fixed in #880 

Thanks for your contribution.

**Pull request closed without merging**
