### PR TITLE
Relocate and restyle 'mature content' filter

### LINKED ISSUE #1033: Change location of the mature content filter in search results
## Description
We need to change how we show the filter that shows/hides mature content on the search result page.

Currently, we have a "Search Settings" filter in the left hand side bar, within which users can enable mature content:
Screen Shot 2020-06-26 at 11 07 51 AM

We want to change the location, design, and interaction of this filter, given its importance. The new location should be in the top right hand corner of the search results page.

[The mockups are available](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=199%3A353&viewport=123%2C72%2C0.06821192055940628) (Mockup - S3) as three pages:
1. Default state.
2. Showing the filter box.
3. Filter activated. (Looks same as default state, i.e. no change when filter is selected).

### Default state
Screen Shot 2020-06-25 at 10 44 29

### Showing the filter box
Screen Shot 2020-06-25 at 10 44 34

### Filter activated
Screen Shot 2020-06-25 at 10 44 42

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Fixes #1033 by @panchovm 

## Description
This PR moves the 'enable mature content' filter from the filters list to a more-prominent position above the search results. The filter _behaves_ identically as previously and has just been moved visually.

## Preview Deployment (in lieu of screenshots)
https://cool.search.zack.cat/search?q=cats

## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by annatuma** [comment]
> Something odd is going on. There's an interaction between the checkbox and the 'mature' tag at the top. If I check the box in the dropdown, a 'mature' tag appears at the top of the page. But, if I click the 'X' to close that tag (or turn it off), then the page reloads with '&mature=False', but the checkbox stays checked. Then, if I click the checkbox, the behavior is inverted from before (I.e., unchecking changes to '&mature=True'.
> 
> It might actually make sense just to remove the 'tag' version completely, since it doesn't make sense here (to me).

I have to admit, I didn't notice in our first implementation of this that we were showing mature as a tag pill. I'm glad you caught this @mathemancer because removing them seems like the right idea (plus it resolves any odd interactions between the filter pills being removed and filters being set/unset).

**Comment by zackkrida** [comment]
Thanks @mathemancer and @annatuma! I didn't love the mature 'tag' either. I fixed its behavior (in the event we ever *did* decide to show it) and removed it. Link updated:

https://cool.search.zack.cat/search?q=horses

**Comment by panchovm** [comment]
Thanks @mathemancer for bringing that. I noticed that during hover state the element moves slightly to right. It looks odd. Is it possible to keep it static?

**Comment by zackkrida** [comment]
@panchovm it seems to be part of a wider issue with button/link shifting on hover. I will take a little time this week to see if it's specifically an issue with Vocabulary or some of the custom, shared styles in `cccatalog-frontend`.

**Comment by zackkrida** [comment]
@panchovm Yes, it's because 'text' buttons have `border: none` on hover where something like `border-color: transparent` would be more appropriate. Removing the border causes a ~2px shift on hovered links. I'll make a separate issue for this; thanks.

**Comment by panchovm** [comment]
Wonderful. Thank you

**Pull request merged**
