### PR TITLE
Added download image link

### PR DESCRIPTION
**Pull request by catherinehoang**
Adds a "download image" link that automatically downloads the image when clicked. I used blobs since the download attribute is blocked for cross domain urls. Works on all browsers.

Fixes issue #172

### CODE REVIEW

**Comment by janeatcc** [comment]
before we deploy this we need to review, maybe add a disclaimer saying the download is downloading directly from the site. please hold

**Comment by janeatcc** [comment]
or let's deploy only to dev for now

**Comment by catherinehoang** [comment]
Sounds good, let me know what you guys decide! I can definitely add a disclaimer if needed.

**Comment by brenoferreira** [comment]
Thank you for your contribution @catherinehoang, but this was done in #208

**Pull request closed without merging**
