### PR TITLE
Switch Axios to Redaxios

### PR DESCRIPTION
**Pull request by abhisheknaiidu**
## Fixes

Related #1075  by @zackkrida 

## Description
Switch Axios to Redaxios
I tried Switching from `Axios` to `Redaxios` by following to the documentation,
But having problem, on actually how exactly we need to implement it, so that's why creating a draft PR.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
Hi @abhisheknaiidu you did exactly what needed to be done. Nice! I'll test this soon, and should be able to merge.

**Comment by zackkrida** [comment]
also need to wait for this pr to go live to push this: https://github.com/developit/redaxios/pull/24

**Comment by abhisheknaiidu** [comment]
> also need to wait for this pr to go live to push this: [developit/redaxios#24](https://github.com/developit/redaxios/pull/24)

Yes exactly, 🙌🏼

**Comment by zackkrida** [comment]
Hi @abhisheknaiidu thanks for doing this, but I'm going to close the PR. I've heard anecdotally from friends about some compatibility issues with `redaxios` and we have other much more significant performance issues to fix than the few `kb` this will save.

**Pull request closed without merging**
