### PR TITLE
Update code to confirm to API v1

### LINKED ISSUE #551: Upgrade to CC Catalog API v1.0
The 1.0 Release of the CC Catalog API is deployed. It has a few breaking changes compared to the old API, which will still be supported for a while, but not indefinitely. Therefore, we should update the frontend code to support this new version of the API.

The API documentation is available at https://api-dev.creativecommons.engineering/v1

All the calls to the API in the frontend are made in [this module](https://github.com/creativecommons/cccatalog-frontend/tree/develop/src/api).

### PR DESCRIPTION
**Pull request by nilshah98**
Fixes #551 

**Changes made**
- Updated API calls from [v0](https://api.creativecommons.engineering/v0/) to [v1](https://api-dev.creativecommons.engineering/v1/)
- Made changes to the different query parameter names, example - provider to sources
- All of the changes have been made either in the `utils/searchQueryTransform.js` or the `store/search-store.js` actions, without affecting the state and props being used by the vue project

**Pending**
- Cannot find endpoint for POST request to `/analytics` in v0 or v1 of the API, but it is being used at `api/UsageDataService.js`
- Response for majority of the API calls are same, have not adjusted for minor tweaks or extra information received like- `attribution` is received in v1, whereas `metadata` is not received, but changes for them haven't been made yet, as I have little idea where to look at.

---

Developer Certificate of Origin Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors. 1 Letterman Drive Suite D4700 San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

### CODE REVIEW

**Comment by brenoferreira** [comment]
Current changes look good.
I mentioned the `/analytics` endpoint issue to @aldenstpage to see what the issue is.

You can also see the differences in the v0 and v1 of the API here https://github.com/creativecommons/cccatalog-api/releases/tag/1.0.0

**Comment by nilshah98** [comment]
I will go through the documentation provided.
Also, will try to fix the code on which the CI tests are failing.

Thanks a lot.

**Comment by nilshah98** [comment]
**Changes**
- Cleaned `search-store.js`, using `...` (spread operator) now
- Updated unit tests to pass all CI tests now

Please review, @brenoferreira

**Comment by brenoferreira** [comment]
This looks good. There are still a couple of things that we need to sort out before we merge. One is with the analytics API, which isn't in the `v1/` namespace. Another is a question for @aldenstpage:
The results for the new https://api-dev.creativecommons.engineering/v1/recommendations/images/47bc8208-c550-40f3-b60f-8eb27ef4bd89 and the old https://api-dev.creativecommons.engineering/image/related/47bc8208-c550-40f3-b60f-8eb27ef4bd89 are quite different. Did the implementation change or are they unrelated endpoints?

**Comment by aldenstpage** [comment]
The endpoint is supposed to be the same implementation, but it looks like a newly introduced routing bug is preventing the right endpoint from being called. You should use it anyway, I'll fix that separately.

**Pull request merged**
