### PR TITLE
Padding-top added to heading in search page 

### PR DESCRIPTION
**Pull request by ayushshivani**
This PR fixes the issue in #224 .
Pr

### CODE REVIEW

**Comment by ayushshivani** [comment]
@brenoferreira Aligning that to left will result in a problem for the desktop view.something like this,
pr1
would result into misalignment in desktop format.
pr2

Will this be okay?
Screenshot from 2019-03-25 22-50-12

**Comment by ayushshivani** [comment]
@brenoferreira I have made the changes requested by you.
finalpr

**Comment by brenoferreira** [comment]
Looks good. Please resolve the merge conflicts and I'll approve and merge

**Comment by ayushshivani** [comment]
@brenoferreira  Done.

**Pull request merged**
