### PR TITLE
Changed position of show mature content filter

### LINKED ISSUE #910: Section Changes on Results Filters
We want to make a few small changes to the Filters on the Results page.

[This is the latest design iteration](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup-S3-License-Language-Changes?node-id=199%3A353).

1) We want to remove the Funnel icon and replace it with "Show/Hide" filters language, per the mockup, to make this action more clear. (This was completed in https://github.com/creativecommons/cccatalog-frontend/pull/867)

2) We're changing the name of "Collections" to "Sources".

3) We're removing the "Settings" section, where the Mature Content filter flag is, and instead placing that at the top right of search results. Addressed here: https://github.com/creativecommons/cccatalog-frontend/issues/1033

### PR DESCRIPTION
**Pull request by Tanuj22**
## Fixes

Partially Fixes #910  by @annatuma 

## Description
Changes the position of the mature content filter. 

## Screenshots
Screenshot from 2020-05-08 03-47-09

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by krysal** [comment]
I was just about to make a PR for this too :) Just one suggestion: you can add `margin-left-small` class to the icon flag to add space from the label text, like in the [mockup](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=242%3A6122).

**Comment by annatuma** [comment]
Good eye @krysal we do indeed want the spacing to match the mockup.

@Tanuj22 thanks for jumping on this, please make that spacing change and then request review again.

**Comment by Tanuj22** [comment]
@annatuma Done :)

**Comment by annatuma** [comment]
Hey @Tanuj22 I just want to note why this hasn't been deployed yet - we're revisiting this placement. After further discussion, it might be better to require an action before accessing this setting to change it, or require additional action after a user selects it, e.g. triggering a modal to confirm the user opting to allow for mature content.

Apologies about this potential change in direction.

**Comment by zackkrida** [comment]
Hi @Tanuj22, thank you for this! The mature content filter was moved to a different part of the UI (above the search results), so I'm going to close this PR. Thank you so much! I promise, I'm going to look at many of your other PRs this week too. Keep them coming! 😸

**Pull request closed without merging**
