### PR TITLE
NSFW filter

### LINKED ISSUE #435: Build filter for NSFW/mature content
See https://github.com/creativecommons/cccatalog-frontend/issues/848 for implementation details.

### PR DESCRIPTION
**Pull request by brenoferreira**
Fixes #435 by @kgodey 

mature

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by aldenstpage** [comment]
(by sheer coincidence, I used that first "cat" result to test the mature filter in the dev environment, so that's why it only appears in the mature results)

**Comment by panchovm** [comment]
Two comments:

- Why there is a Settings category for only one filter? The categories should include more than one element. Otherwise, it could be shown as the `Search by Creator` filter.
- The section where filters appear neither have the label **Filter by** nor the gray background

**Comment by brenoferreira** [comment]
@panchovm the Settings thing is how it's described in the issue (See "Filter" in #848). The Filter By is a bug. Thanks for spotting it. I'll fix it

**Comment by brenoferreira** [comment]
mature
_fixed_

**Comment by brenoferreira** [comment]
@akmadian the results come from the API. I think the filter will work better as more images are classified as nsfw. @aldenstpage can clear it up better for you

As for the alignment, can you open an issue so that this can be done separately

**Comment by aldenstpage** [comment]
@akmadian In this initial pass, we don't have any way to automatically identify an image as NSFW, we just created the means to flag an image manually and exclude them from the search results. In the future we'll use keywords to flag potential NSFW images. This ticket has some details: https://github.com/creativecommons/cccatalog-api/issues/482

**Pull request merged**
