### PR TITLE
Update FooterSection.vue

### LINKED ISSUE #1117: Change logo display markup in the footer
## Problem

Change logo display markup in the footer. 

## Description

Currently we use an svg with a ```<use>``` tag to display the logo, but this results in a reduced accessibility score as that element does not have a useful aria-label. The common practices of setting ```aria-role="img"``` and providing a title also don't work in this scenario.

Also it is not recommended to use svg with ```<use>``` for better accessibility purposes [Accessible SVG](https://css-tricks.com/accessible-svgs/#2-inline-svg)

## Alternatives

We might convert the logo to use with an `````` tag or use a standardized svg format.

## Additional context

Lighthouse Report
```
Links do not have a discernible name
Link text (and alternate text for images, when used as links) that is discernible, unique, and focusable improves the navigation experience for screen reader users.
Failing Elements
--
a<a class="main-logo" href="https://creativecommons.org" target="_blank"><div class="has-text-white"><svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid meet" viewBox="0 0 304 73"> <use href="#logomark"></use> </svg></div></a>
```

## Implementation

- [x] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by neeraj-2**
## Fixes

Fixes #1117 by @AyanChoudhary 

## Description

Performance has been improved as per Lighthouse Report

## Technical details

Changes in footer has been done !

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by AyanChoudhary** [comment]
@neeraj-2 looks like the tests are failing

**Comment by neeraj-2** [comment]
> @neeraj-2 looks like the tests are failing

@AyanChoudhary should i create a new PR?

**Review by neeraj-2 — COMMENTED** [review]
Seems good now @AyanChoudhary  and @zackkrida ,Please review and merge if it is Okay.

**Review by zackkrida — APPROVED** [review]

**Comment by zackkrida** [comment]
Great work @neeraj-2! Merged.

**Comment by neeraj-2** [comment]
> Great work @neeraj-2! Merged.

Thank you @zackkrida

**Pull request merged**
