### PR TITLE
[META] Internationalization (i18n) Setup 

### LINKED ISSUE #487: [META] Internationalisation (i18n) Setup
This should be about adding i18n support, not the translations themselves.
Even if we continue supporting only English initially, it's good to have support for i18n and do the translations later.

Sub-tasks:

- [x] Set up vue-i18n infrastructure: installing [vue-i18n package](https://kazupon.github.io/vue-i18n/) and setting up the internationalization infrastructure on both client and server renderers (See #941)
- [x] Create the translations JSON message object schema, research which [formatters](https://kazupon.github.io/vue-i18n/guide/formatting.html) will be required to render text and numbers. (See #942)
- [x] Allow users to change locale on the client (See #943)
- [x] Set up translation service infrastructure, as of this writing, with https://www.transifex.com/ (See #944)
- [ ] Set up locale detection on the server to load appropriate localized messages (See #945)

### LINKED ISSUE #941: Set up vue-i18n infrastructure
[Install vue-i18n](https://kazupon.github.io/vue-i18n/installation.html) and set up a simple translation of one piece of text in the application (eg: the `SEARCH FOR CONTENT TO REUSE` on the home page). See the [Getting started guide](https://kazupon.github.io/vue-i18n/started.html#html) documentation

### LINKED ISSUE #942: Create locale messages format JSON structure
Once the Vue-i18n infrastructure is setup, the [locale message format](https://kazupon.github.io/vue-i18n/guide/formatting.html) JSON structure needs to be defined.

Because once this is setup, text changes won't be done in the components themselves, but rather in this JSON file. The structure needs some logical order so that it's easy to find in this large JSON object a particular piece of text, otherwise it quickly becomes very hard to maintain.

One possible structure could be:

```
// this is a suggested example and not the complete structure
{
  // text that could be reused on multiple components
  licenses: {
    by: "Credit the creator",
    sa: "Share adaptations under the same terms",
    ...
  },
  navbar: {
    about: "About",
    collections: "Collections",
    ...
  },
  footer: {
    ...
  },
  // then break in page and components
  
  home_page: {
    header: "SEARCH FOR CONTENT TO REUSE",
    input_placeholder: "I would like to see",
    search_button: "Search",
    ...
  },
  photo_details_page: {
    back: "Back to search results",
    tabs: {
      reuse: {
        title: "Reuse",
        license: "License",
        description: 'This image was marked with a {license} license',
        ...
      }
    }
  }
  ...
}
```

### LINKED ISSUE #943: Allow users to change locale on the client
Allow users to select a preferred language in the UI, and load the locale data accordingly.

Initially, we could load the site in English by default when the user access https://ccsearch.creativecommons.org/.

And different locales could be loaded with a locale key in the URL, such as:

* https://ccsearch.creativecommons.org/es for Spanish
* https://ccsearch.creativecommons.org/fr for French
* https://ccsearch.creativecommons.org/pt for Portuguese,
etc.. [List of locale codes](https://www.science.co.il/language/Locale-codes.php)

The design of the language chooser is available in [Figma](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=753%3A0), but where exactly it's placed in the CC Search UI is still to be decided

### LINKED ISSUE #944: Set up translation service infrastructure
Set up the infrastructure to allow the use of the translation service https://www.transifex.com/.

It seems like the only integration provided by Transifex that could help in the case of this project is the [Github Integration](https://docs.transifex.com/transifex-github-integrations/github-tx-client), which seems to support translations in a .json file

### PR DESCRIPTION
**Pull request by AyanChoudhary**
## Fixes

Fixes #941 by @brenoferreira 
Fixes #942 by @brenoferreira 
Fixes #943 by @brenoferreira 
Fixes #944 by @brenoferreira 
Fixes #487 by @brenoferreira 

## Description

Setup the vue-i18n plugin to enable the internationalization of the cc-search website.

## Screenshots

Design Library – Figma - Brave 06-06-2020 00_23_40

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kgodey** [comment]
Please merge this into a temporary branch instead of `develop` so that we can make releases from develop without merging in partial i18n work.

**Comment by akmadian** [comment]
Okie dokie, all PRs have been merged! Please resolve the merge conflicts and do some last minute cleanup if it's needed, then @ me and @zackkrida so we can do final reviews before merging this :) @AyanChoudhary

**Comment by AyanChoudhary** [comment]
@akmadian @zackkrida I am done with rebase and have fixed some formatting issues as well, this is ready for the final review.

**Comment by AyanChoudhary** [comment]
@zackkrida thanks for pointing those out, even I was not sure about the placement of the locale-selector @panchovm maybe you can help with the 1st and 3rd points above. I might have missed **credit the creator** part, I will see to it today itself.

**Comment by panchovm** [comment]
You are right @zackkrida, it makes sense to have it across all pages of a site. Users should be able to change the site's language whenever they are. We have not discussed this so thanks for bringing it. In general, we have not thought about responsive components. Let me see @AyanChoudhary  how we can face this because this has been a redundant issue.

**Comment by zackkrida** [comment]
As discussed, we will be redesigning the locale chooser to be a part of the global site header! Should be cool.

**Comment by zackkrida** [comment]
@AyanChoudhary, terribly sorry about the insane # of merge conflicts. I just merged in a PR to add code formatting via prettier, and felt this was the best time to do it (since there are so few pending PRs). I'll find a good way to fix these conflicts in bulk so you don't have to touch nearly every file in the codebase 😆

**Comment by zackkrida** [comment]
@AyanChoudhary think i got it, if anything looks broken just feel free to remove my last commits and we will figure it out. Thank you!

**Comment by AyanChoudhary** [comment]
@zackkrida sorry for replying back a little late. The changes don't break anything. And thanks for integrating those.

**Comment by AyanChoudhary** [comment]
@zackkrida was waiting for the confirmation, will do it as soon as possible.

**Comment by AyanChoudhary** [comment]
@zackkrida looks like I broke a couple of things while fixing the large amount of merge conflicts 😥, the things which look to be broken are:
1. the alignment of elements in the footer
2. the hide filters button

Surprisingly everything else is intact. I will fix these two as well.

**Comment by zackkrida** [comment]
No problem, we will figure it out this week!

**Comment by AyanChoudhary** [comment]
Fixed those as well 😁

**Pull request merged**
