### PR TITLE
Added Modal to filter form

### LINKED ISSUE #684: Filter button issue under responsive view.
(All things under-responsive views)

When we search an item, and scroll down and then click on the filter icon, which is floating on the top-right, It does nothing, being more specific, it expands the filter section, but at top=0, so it seems that nothing happens.

Screenshot (182)

So the fix should be, when we click on the filter button, it should take us to the top, where the filter section is expanded. 

OS- Windows 10
Browser - Chrome 

Will take up this issue!

### PR DESCRIPTION
**Pull request by abhisheknaiidu**
Fixes #684 

mobile

desk

Developer Certificate of Origin Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors. 1 Letterman Drive Suite D4700 San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

### CODE REVIEW

**Comment by abhisheknaiidu** [comment]
@akmadian  am I allowed to make it more accessible by adding aria-tags or it will be done during Outreachy/Summer of code ?

**Comment by abhisheknaiidu** [comment]
@akmadian I have made changes for both Mobile and Desktop Version, Yea I have sticked the filter sidebar on the desktop version.
And talking to the Mobile version I think I somewhat recreated Francisco's Mockup except for 2 things :
i) Uses drop-down menu just like the desktop version in order to see more menu's to the user before clicking any filter
ii) Close button icon, for this, am I allow to use font-awesome or any image? or is this fine?

**Comment by abhisheknaiidu** [comment]
Sorry @akmadian I need to open another PR, because of some `branch conflicts`
you can take a look #866

**Comment by brenoferreira** [comment]
This looks like a duplicate of #866. Can I close this @abhisheknaiidu ?

**Comment by abhisheknaiidu** [comment]
Yess sure @brenoferreira and sorry for inconvenience created!

**Pull request closed without merging**
