### PR TITLE
Removed some licences based on Use category

### LINKED ISSUE #845: Updates to Results Page
We want to make some changes to the Results page in CC Search.

These changes apply only to the Filter side bar on the Results page. 

Reference the following screens in Figma when going through the list, to understand what these changes entail:
Results commercially
Results modify
Results license (for modal)
License Filter update

See mockups in [Figma](https://www.figma.com/file/0tnxdVJPRUhDJCN0LO8P5d/Mockup---Sprint-2?node-id=0%3A286).

These are the changes we want to implement:

- [x] Move the expand/collapse filter icon into the Filter side bar when expanded. (It is currently to the right of the side bar, in line with the search bar). (Complete: https://github.com/creativecommons/cccatalog-frontend/pull/867)

- [x] Add title to Filter side bar: “Filter results by”. (Complete: https://github.com/creativecommons/cccatalog-frontend/pull/867)

- [ ] Allow users to filter by both Use and License
- [ ] -- If “Use commercially” is checked, NC licenses should not be available for selection from License filter.
- [ ] -- If “Modify or adapt” is checked, ND licenses should not be available for selection from License filter.

This was being addressed in https://github.com/creativecommons/cccatalog-frontend/pull/867 but there was a misunderstanding regarding the proposed functionality.

- [x] Update the License filter, to include the License icons, as well as the License abbreviation, for example as shown in the “License Filter update” screen. (Done: https://github.com/creativecommons/cccatalog-frontend/pull/989)

- [x] Add question mark icon to each license, with modal on hover, which shows bullets per license, styled as indicated in “Results license” screen. (Done: https://github.com/creativecommons/cccatalog-frontend/pull/989 but there are some styling issues, which will be dealt with separately: https://github.com/creativecommons/cccatalog-frontend/issues/1047)

- [x] Add visual indicators to Aspect Ratio filter, for tall, wide, square, as shown in mockup. (Done: https://github.com/creativecommons/cccatalog-frontend/pull/989)

Please note that we do not want to change the background color of the Filter side bar, that should remain as it currently is.

### PR DESCRIPTION
**Pull request by abhisheknaiidu**
## Fixes

Partially Fixes #845  by @annatuma 

## Description
Allowed users to filter by both Use and License

- If “Use commercially” is checked, NC licenses should not be available for selection from License filter.

Screenshot 2020-07-20 at 3 39 06 AM

- If “Modify or adapt” is checked, ND licenses should not be available for selection from License filter.

Screenshot 2020-07-20 at 3 39 33 AM

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by abhisheknaiidu** [comment]
@zackkrida Could you review this also?, i don't know why `prettier` checks are failing

**Comment by AyanChoudhary** [comment]
@abhisheknaiidu run ```npm run format``` before committing your changes and prettier will do the linting changes

**Comment by abhisheknaiidu** [comment]
@AyanChoudhary Thanks, It worked 😃

**Comment by zackkrida** [comment]
Hi @abhisheknaiidu this looks good so far, but I will have to wait to merge, as I need to discuss some of this functionality with @annatuma who is on vacation for a few days.

**Comment by zackkrida** [comment]
@abhisheknaiidu I can give you some more information now. You may continue work. The behavior _before_ you built this was already incorrect, so there are some adjustments to make:

1. If “Use commercially” is checked, NC licenses should be _disabled_. The other licenses should not be disabled.
2. If “Modify or adapt” is checked, ND licenses should be _disabled_ for selection from License filter.
3. If no licenses are chosen, “Use commercially” and “Modify or adapt” are both enabled.
4. If any ND licenses are chosen, “Modify or adapt” should be disabled.
5. If any NC licenses are chosen, “Use commercially” should be disabled.

**Comment by abhisheknaiidu** [comment]
> @abhisheknaiidu I can give you some more information now. You may continue work. The behavior _before_ you built this was already incorrect, so there are some adjustments to make:
> 
>     1. If “Use commercially” is checked, NC licenses should be _disabled_. The other licenses should not be disabled.
> 
>     2. If “Modify or adapt” is checked, ND licenses should be _disabled_ for selection from License filter.
> 
>     3. If no licenses are chosen, “Use commercially” and “Modify or adapt” are both enabled.
> 
>     4. If any ND licenses are chosen, “Modify or adapt” should be disabled.
> 
>     5. If any NC licenses are chosen, “Use commercially” should be disabled.

@zackkrida It should be disabled or we don't have to show them? because @annatuma said, we don't need to show it, i guess in #845

**Comment by zackkrida** [comment]
Yes @abhisheknaiidu she said 'not be available' which is definitely up for interpretation, but I think disabling is more clear than completely hiding.

In the future I think we could implement some kind of tool tip that says _why_ an input is disabled: something like "Can't select NC licenses when 'use commercially' is selected".

**Comment by abhisheknaiidu** [comment]
@zackkrida ok cool, will do the changes, as you said 😊

**Comment by abhisheknaiidu** [comment]
@zackkrida Done i think so, could you once review this?

**Comment by annatuma** [comment]
Thanks @abhisheknaiidu for working on this, and @zackkrida for running point on understanding what I meant regarding disabling. Disabling was definitely the intended behavior, apologies for the lack of clarity.

I think the tooltip when licenses are disabled is a great idea. @abhisheknaiidu are you up for thinking about what that might look like and creating a ticket with a proposal?

**Comment by abhisheknaiidu** [comment]
@annatuma yes that actually makes sense, It's better to disable `Tooltip` as well, for better UX 
So, should I directly do a PR, or create a new `ticket`, then PR? @zackkrida

**Comment by zackkrida** [comment]
@abhisheknaiidu please create a ticket first, thanks!

**Pull request merged**
