### PR TITLE
Switched vuejs-accessibility plugin

### LINKED ISSUE #1241: Switch from `eslint-plugin-vue-a11y` to `eslint-plugin-vuejs-accessibility`
## Problem

As described by @obulat [here](https://github.com/creativecommons/cccatalog-frontend/pull/1240#issuecomment-707669159), `eslint-plugin-vue-a11y` is no longer maintained, and has been supplanted by https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility. We should switch plugins, and make sure everything is working correctly.

### PR DESCRIPTION
**Pull request by ritesh-pandey**
## Fixes

Fixes #1241 by @zackkrida 

## Description

Switches vuejs-accessibility plug-in from `eslint-plugin-vue-a11y` to `eslint-plugin-vuejs-accessibility`

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — CHANGES_REQUESTED** [review]
Thank you for working on this, @ritesh-pandey !

I think we can merge this PR if we set  'vuejs-accessibility/aria-role' in .eslintrc.js to 'warn'.

We would have only two types of warnings left:
1. In the App modal the error is 'click events should have associated keyboard events'. However, we have a `@keyup` handler there, so I'm not sure why it causes an error.
2. Incorrectly added role for a tag button in 'Filterblock.vue'. We should remove `role=filter`, because such a role does not exist for a button. Also, while we are editing these files, we can as well fix the labels for screen readers.  These tag buttons clear a filter when clicked, so we should add `aria-label="'remove ' + label + 'filter'`.

**Comment by ritesh-pandey** [comment]
Should we also remove `eslint-plugin-vue-a11y` and its traces or take it as separate task?

**Comment by ritesh-pandey** [comment]
Only one error remains now
```
/home/ritesh/github/ritesh-pandey/cccatalog-frontend/src/components/AppModal.vue
  2:3  error  Visible, non-interactive elements with click handlers must have at least one keyboard listener  vuejs-accessibility/click-events-have-key-events

✖ 1 problem (1 error, 0 warnings)

```

**Comment by obulat** [comment]
> Should we also remove `eslint-plugin-vue-a11y` and its traces or take it as separate task?

I think it would be better to remove it in this PR.

**Review by zackkrida — APPROVED** [review]
Great work everyone! I added an `eslint-disable` comment to the line in `<AppModal>` that was giving us issues. And also fixed some a11y issues in the modal while I was here.

**Pull request merged**
