### PR TITLE
Adds functionality to take users back to where they left

### LINKED ISSUE #184: clicking back to search results takes user back to top of list vs place they left off
"I've been finding that when I search in CC Search and then go "back to results" it takes me back seemingly to the top of the whole list and I have to find where I was before, which is a bit tedious" --@evarogers

### PR DESCRIPTION
**Pull request by SomtochiAma**
Fixes #184

[Short description explaining the high-level reason for the pull request]
It returns the user to twhere they left off versus the top of the list

### CODE REVIEW

**Comment by brenoferreira** [comment]
When scrolling 2 or 3 pages down, this solution doesn't work. I think this requires a different solution, maybe even changing the scrolling mechanism

**Comment by SomtochiAma** [comment]
Okay true. I see that now. Should I close the PR?

**Comment by brenoferreira** [comment]
If you're planning on not moving forward, then please do

**Comment by SomtochiAma** [comment]
I still do. Do you have any suggestions for implementing a different solution?

**Comment by brenoferreira** [comment]
I don't have anything at the moment. I would have to think about it

**Comment by annatuma** [comment]
This was completed elsewhere. Closing pull request.

**Pull request closed without merging**
