### PR TITLE
Removed 'license' from PDM and CC0 in reuse tab and filters

### LINKED ISSUE #1099: Fix Text on Reuse Tab for CC0 and PDM
## Problem

When we implemented new license descriptions on the Reuse tab of the single result page in CC Search, we did not include the correct language for the public domain tools CC0 and PDM. This needs to be fixed.

## Description

The text that was requested for implementation is in [this Google Doc](https://docs.google.com/document/d/14NoqosLebbIIZFR9y7e0-qJsqHO1lelZwZl2J0MBDE4/edit).

For CC0 and PDM, the text needs to reference tools and not licenses. **Note that CC0 is a tool and not a license, which is why the language needs to be different.**

This is what the Reuse tab currently looks like for CC0, with markings to indicate the errors:

reuse tabs update

### LINKED ISSUE #1100: Remove "License CC" from CC0 and PDM Modals on Filters
## Problem

We are currently using license language for CC0 and PDM, which are actually legal tools and not licenses, on the informational modals in the filter side bar.

## Description

We need to remove "License CC" from the top line of the modal, leaving just the name of the tool. We also need to change the link to say "tool" and not "license". Screenshots indicate changes:

pdm in license filters
cc0 in license filters

### PR DESCRIPTION
**Pull request by rochisha0**
## Fixes

Fixes #1099 and Fixes #1100  by @annatuma 

## Description
This PR removes the 'license' word from PDM and CC0 as described in the issues.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by rochisha0** [comment]
Hey, @zackkrida ! This has to be fixed for specifically for CC0 and PDM or in general?

**Comment by zackkrida** [comment]
Cco and pdm, good question! For everything else it should still say 'license'

**Comment by rochisha0** [comment]
@zackkrida Done all the changes!

**Comment by zackkrida** [comment]
@rochisha0 awesome, I really like how you handled that, with a separate translation string for tools. great idea!

**Pull request merged**
