### PR TITLE
added padding in info text for mobile view

### LINKED ISSUE #625: Info text has no padding in horizontal direction in mobile view
## Describe the bug
In mobile view, when select info view of an image, then in mobile view it don't have padding

## To Reproduce
1. Go to 'search on results'
2. Click on 'any result'
3. Scroll down to 'to info tab'

## Expected behavior
Info text should have some padding in horizontal direction

## Screenshots
Screenshot_2020-02-24 CC Search

## Smartphone (please complete the following information)
 - Device: (ex. iPhone6)
 - OS: (ex. iOS8.1)
 - Browser (ex. stock browser, safari)
 - Version (ex. 22)

## Additional context
I would like to work on it

### PR DESCRIPTION
**Pull request by Vineet-Sharma29**
added padding in horizontal direction in info text for mobile view

Fixes #625 #632 #678 #679 

- for `.tabs-content` class, in mobile view changed `padding:30px 0` to `padding:30px 15px`
-  editted `.photo_tag` class in mobile view appropriate margins have been added
- added `display:flex` in `.tabs` class for `mobile-sm` view
- for styling legal section, added `ul` tag

**Before**
Screenshot_2020-02-24 CC Search(1)

**After**
Screenshot_2020-02-29 CC Search(3)

---

Developer Certificate of Origin Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors. 1 Letterman Drive Suite D4700 San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

### CODE REVIEW

**Comment by Vineet-Sharma29** [comment]
@akmadian I have fixed responsive error for tablet view as well. What I understood from your first error review is image in photo detail view is has unnecessary padding, I have that unnecessary padding.

**Comment by akmadian** [comment]
I mentioned that provider logos were not showing, but I think that's because you forked the repo before #614 was merged, which would explain it. So, nevermind about the provider logos!

**Comment by Vineet-Sharma29** [comment]
@akmadian Fixed responsive error in tablet view. In order to avoid collision with scrollbar fix #632 handles it

**Comment by akmadian** [comment]
I was going to do a review on this today, but I just realized that this could potentially be influenced by #661, so I think we should both pause on this until after 661 is merged. After, you can go back and check if any of these issues have been fixed in 661, and if you need to modify any of your changes based on syntax changes in 661.

**Comment by Vineet-Sharma29** [comment]
@akmadian okk.

**Comment by Vineet-Sharma29** [comment]
@akmadian #661 has solved #625 #632 . Therefore I will close them. Shall i remove changes made as per #678.

**Comment by akmadian** [comment]
@Vineet-Sharma29 No, since tab wrapping is intended. I don't think we'd accept what I currently see in this PR, but if you have another idea for the tabs, please provide a screenshot in #678

I'm gonna close this PR, if we decide to move forward with changing the tabs, please open a fresh one. Thanks for all your work on this, even though it's not been merged so far :)

**Pull request closed without merging**
