### PR TITLE
Addition of Donation Banner

### LINKED ISSUE #1199: Add Donation Banner to top of CC Search
We'd like to add a Donation banner to the top of CC Search, to help drive community support for the project.

[Design](https://www.figma.com/file/y09nZth7u1a75xO9sLtjcw/Mockup---S5-(Source-and-provider)?node-id=1606%3A0).

The "Yes..." button should link to this form: https://www.classy.org/give/297881/#!/donation/checkout

The "Not Today" button and the "X" should close the banner.

We should show the banner once per session, meaning that if a user chooses to close the banner, we should remember that for the duration of their session. This banner should be visible on every page on CC Search, unless closed.

For smaller screen sizes, let's go with logical break points, doing line breaks for text on the left, and stacking the buttons on the right.

### PR DESCRIPTION
**Pull request by neeraj-2**
## Related to

Fixes #1199 by @annatuma 

## Description

I have added a Donation Banner here.

## Technical details

The donation Banner is visible unless user will close it.It user clicked on "Yes i 'll donate now",the user will be redirected to link "https://www.classy.org/give/297881/#!/donation/checkout".

##Demo:
ezgif com-gif-maker

## Checklist
 
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
Hi @neeraj-2, you wrote a lot of custom styles. CC Search is built on [vocabulary](https://cc-vocabulary.netlify.app) which has a ton of built in classes and components to help you, so you don't have to hard code colors, spacing, etc. yourself. Please look at vocabulary and try switching some of your styles over!

**Comment by neeraj-2** [comment]
> Hi @neeraj-2, you wrote a lot of custom styles. CC Search is built on [vocabulary](https://cc-vocabulary.netlify.app) which has a ton of built in classes and components to help you, so you don't have to hard code colors, spacing, etc. yourself. Please look at vocabulary and try switching some of your styles over!

ok,@zackkrida i will do that .

**Comment by neeraj-2** [comment]
@zackkrida  now i did not use custom styles,can u please tell me why the tests are failing ?
:(

**Comment by zackkrida** [comment]
Yes @neeraj-2 i will let you know once I review!

**Comment by neeraj-2** [comment]
@zackkrida  i have created a new draft pr for it #1219,that's why i closed it

**Pull request closed without merging**
