### PR TITLE
h5_replaced(fixes #1118)

### LINKED ISSUE #1118: Proper ordering of <h> tags in the pages
## Problem

We need to have a proper ordering of the ```<h>``` tags. Currently, we have an ```<h5>``` tag in the footer and an ```<h1>``` or ```<h2>``` tag in the page. Ideally to satisfy accessibility requirements we need to have the ```<h>``` tags in a definite order i.e. an ```<h5>``` tag should have preceding ```<h1> ... <h4>```tags.

## Additional context

This is actually reducing our accessibility scores by quite a bit.

## Implementation

- [x] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by Aakash2408**
## Fixes

Fixes #1118  by @AyanChoudhary 

## Description

  Before the changes, we have an h5 tag in the footer and this has been changed to <span> without affecting changes in 
  frontend. 
  It has some CSS properties as it has with h5 tag.

## Tests

  Check if there is span tag used in replacement of h5 tag  on line 150 on the location https://github.com/creativecommons/cccatalog-frontend/blob/develop/src/components/FooterSection.vue 

## Screenshots

Screenshot from 2020-08-18 21-09-46

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Aakash2408** [comment]
> hi @Aakash2408 this is a good start. Instead of writing custom styles, you could use some css classes that will mimic an h5 tag `title is-5`. You will need styles for `color: #fff;` after switching to the classes though.

 Can you please tell me what you mean by title-5 here?

**Comment by zackkrida** [comment]
@Aakash2408 `title` and  `is-5` are two css classes you can put on the `<span>` that will make its styling match an `<h5>` tag

**Comment by Aakash2408** [comment]
> @Aakash2408 `title` and `is-5` are two css classes you can put on the `<span>` that will make its styling match an `<h5>` tag

ok ok, I was just checking title class and was going to put that and  font size manually but is-5 class will fulfill that! Thanks, I will just do it.

**Comment by zackkrida** [comment]
@Aakash2408 does `has-text-white` work for you locally? it doesn't actually change the text color for me

**Comment by Aakash2408** [comment]
> @Aakash2408 does `has-text-white` work for you locally? it doesn't actually change the text color for me

I checked this in locals and it worked actually this class is already used in the same footer component so ya it works!

**Comment by Aakash2408** [comment]
> @Aakash2408 does `has-text-white` work for you locally? it doesn't actually change the text color for me

Screenshot from 2020-08-18 22-27-43

**Pull request merged**
