### PR TITLE
Add support us page

### LINKED ISSUE #1201: Create "Support Us" page
We'd like to create a new page on CC Search called "Support Us".

It should be linked from the top nav, on the far right.

[Page mockup](https://www.figma.com/file/y09nZth7u1a75xO9sLtjcw/Mockup---S5-(Source-and-provider)?node-id=1585%3A4340)

[Text content including link information](https://docs.google.com/document/d/1pOllcRm9PkI-ZSztdLXclXVVa5wRTVPl9XVS5fpG6UA/edit?usp=sharing).

Please note that the design is _not_ pixel perfect, but displays how the content should be laid out and spaced, and where donation buttons should be placed.

### PR DESCRIPTION
**Pull request by rochisha0**
## Fixes

Fixes #1201 by @kgodey 

## Description

It adds a 'support us' page.

## Screenshots

image

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — CHANGES_REQUESTED** [review]
Great work @rochisha0. One thing: could you avoid writing text in ALL CAPS, and instead use `text-transform: uppercase` in css or bulma's `.is-uppercase` class to make test all caps? All caps in html can have accessibility issues (some screen readers read ALL CAPS like acronyms (A.L.L C.A.P.S) where it reads each letter out loud).

The other thing is, the donate buttons have a bug in vocabulary. They have _no_ border instead of a 1px yellow border. I'll make an issue for that. That will make sure they align correctly here:

Screen Shot 2020-09-10 at 8 36 54 AM

**Comment by rochisha0** [comment]
Thanks, @zackkrida ! I have done the changes. One more thing the subtitle classes render differently in the browser while using exactly the same way. What could be the reason for the discrepancy? Or I'm missing something?
image

**Comment by zackkrida** [comment]
The `.content` class takes the bold off of heading tags. Another vocabulary bug!

**Comment by rochisha0** [comment]
Oh! That was my mistake I have fixed that! Thanks again @zackkrida  !

**Comment by KarenEfereyan** [comment]
@rochisha0 this is some nice work

**Review by zackkrida — APPROVED** [review]

**Pull request merged**
