### PR TITLE
Download polaroid watermark

### LINKED ISSUE #207: Add link to download watermark with attribution
Add a link in the photo details page that lets users download the image inside a frame containing the proper author attribution and license.

Link to the API issue https://github.com/creativecommons/cccatalog-api/issues/209 and PR https://github.com/creativecommons/cccatalog-api/pull/214

### PR DESCRIPTION
**Pull request by brenoferreira**
Link on the photo details page to download the watermark with attribution

Fixes #207

### CODE REVIEW

**Comment by brenoferreira** [comment]
watermark
_downloading watermark_

watermark
_watermark image_

**Comment by janeatcc** [comment]
should only be deployed on ccsearch-dev first. final review by me + legal is required before deploying to production

**Comment by janeatcc** [comment]
let's call it "attribution in frame" or similar

**Comment by kgodey** [comment]
@brenoferreira I think it would be good to update the code to refer to the name Jane's provided instead of "watermark".

**Comment by brenoferreira** [comment]
@kgodey in the code, it's all referred to as `watermark`

**Comment by janeatcc** [comment]
Change "ACTIONS" text to "PHOTO DOWNLOAD"

**Comment by kgodey** [comment]
I would recommend "IMAGE" instead of "PHOTO" because the image might be artwork or something else that isn't a photo.

**Comment by janeatcc** [comment]
That's fine -- then please change it on the other two headings to be consistent. So "IMAGE INFO" and "IMAGE ATTRIBUTION"

**Comment by brenoferreira** [comment]
Screen Shot 2019-03-19 at 21 16 42
@janeatcc ☝️

**Comment by janeatcc** [comment]
looks good! we can push the other headings to production but keep the watermark feature flagged :)

**Pull request merged**
