### PR TITLE
Meta search

### LINKED ISSUE #921: [META] Add meta search to CC Search
## Problem Description

Prior to CC Search coming out of beta a year ago, CC offered a meta search of CC-licensed content from a number of sources that either have content types not yet supported by CC Search, or that do not have APIs allowing us to index their content.

See some earlier discussion in this ticket https://github.com/creativecommons/cccatalog-frontend/issues/315 for context.

## Solution Description

The solution is two fold:

1) For content types that _are_ available in CC Search, we want to add the option for users to carry out a meta search via a modal. For launch, the link to this modal will be placed directly below the "Load More Results" button at the bottom of the first page of search results. At launch, this means that the modal will only be integrated for images. Ticket https://github.com/creativecommons/cccatalog-frontend/issues/922

2) For content types that _are not_ available in CC Search, we want to add meta search directly in the existing UI, with messaging around what the user can expect, starting with audio and video. Ticket https://github.com/creativecommons/cccatalog-frontend/issues/923

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes
Fixes #921 

## Description
Implements legacy meta search for images, audio, and video.

## Preview Url

https://coolsearch.zackkrida.vercel.app

## Testing notes

- In addition to reviewing code, please review the preview url provided with the following steps:
  - Make a search
  - Visit the audio + video tabs and the various external links
  - Scroll to the bottom of the image results and click the "Not finding what you need? Search other sources" link, visit external providers
  - Note: "Use" filters in the sidebar only apply to Europeana, Soundcloud, and Google. Other providers do not offer granular filtering by use case. Please check these filters and make sure they apply as you would expect them to.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by panchovm** [comment]
It looks great and the flow works correctly. Answering your questions:
* Sorting providers alphabetically is a good idea. Let's go with that.
* Showing provider's names is enough. And it matches the Sources page we will have.

And comments regarding design:
1. We need to eliminate the link that goes to **old CC Search** in home page. 
2. The hover state of the link below `Load more results` button should have an underline style. I think it's a component issue.
3. In the modal design, the title **Search images…** doesn't use `Heading 3A` style.
4. In the modal design, the **Source** title doesn't use `Heading 5B` style.
5. The content in Audio tab is not left-aligned. I think this a grid issue. Below I added a screenshot.
6. In Audio tab the text "CC Search does not..." is using a different text style, but it looks good as it is now. It doesn't need change. 

## Screenshot
Point 5.
Screen Shot 2020-07-17 at 11 16 04

Should I create tickets @zackkrida for the issues mentioned above?

**Comment by zackkrida** [comment]
@panchovm Thank you! No issues needed, I will just fix here. I appreciate your attention to detail

**Comment by kgodey** [comment]
Are we replacing the Old CC Search link with any sort of notice that we're now supporting the functionality in current CC Search? if we don't do that, people might be confused.

**Comment by zackkrida** [comment]
@kgodey @panchovm Anna and I actually discussed the idea of creating a page on cc search (not part of the nav, just replacing the 'old cc search') link explaining that old cc search is or will be deprecated.

I think we have to decide if we want to immediately deprecate old search, or have meta search live side by side with old cc search for a brief period. Since parts of old cc search are already broken, I'm leaning towards immediately shutting it down, but we may want to have some old search users weigh in.

I'm sure @annatuma has better ideas for this as well.

**Comment by panchovm** [comment]
I like the idea of explaining that old cc search is or will be deprecated, but not sure about creating a new page. I will put that information in the About page.

I understand that some users might be confused, but updating and evolving CC Search (or any product) implies changing functionalities and flows. From a UX perspective, it is clear and enough the flow we created. Regarding deprecate or live side by side the old search, I prefer deprecate it. The endless transition can generate confusion.

**Comment by zackkrida** [comment]
@panchovm A section on 'about' could be a very good idea, we could link to the specific section

**Comment by kgodey** [comment]
I agree with deprecating old CC Search immediately. However, the "old CC Search" link was on the homepage, and you don't see meta search from the homepage. People will think the functionality is gone entirely and may not perform a search to realize that meta search functionality is now integrated into current CC Search, and we may lose users. I think we probably need some sort of temporary notice on the homepage for those users.

cc @panchovm @annatuma

**Comment by zackkrida** [comment]
@kgodey The leading idea (okay, i'm making this up, combining ideas from @annatuma and @panchovm) is that the homepage says something like 'Coming from old cc search? Learn more' and links to `/about#meta-search` or whatever, which is a section describing the deprecation of old search and introducing meta search. 

That section would have two inline gifs of the meta image flow and the meta audio/video flow.

**Comment by annatuma** [comment]
Please don't remove the current link from the homepage to old CC Search as part of this PR. Old CC Search also will not be offlined immediately. We do need to do community education, and explain how this all hangs together.

I don't have time to dive into the "how" before the end of the day/week, so for now, please simply don't remove that link from the CC Search homepage. We will tackle that change of flow and accompanying communication separately.

**Comment by kgodey** [comment]
I like @zackkrida's idea but I too think it's best to do the old CC Search deprecation in a separate step. Let's leave the link for now.

**Comment by zackkrida** [comment]
@kgodey i am going to merge meta search, i will likely have you review when checking the devsite prior to release. Thanks 😄

**Pull request merged**
