### PR TITLE
Added Bug Report Form in Feedback tab

### LINKED ISSUE #244: Embed Bug Report form in Feedback tab on CC Search
**Feature Description**
We'd like to make an update to our Feedback page on CC Search. The page is split into two sections: Feedback and Report a Bug. The Feedback section has an embedded Google Form. We'd like to add a second embedded form to the Report a Bug section.

Link to form to embed: https://docs.google.com/forms/d/e/1FAIpQLSeSN1AIG8LrdgIdKpBj4IlPDhu6T5ndZ7z_QcISBu-ITCU0Yw/viewform

Let's also remove this content from the Report a Bug section:
"If you would like to report a bug you are encountering when using the tool, please email support-search@creativecommons.org or log the issue directly at Github."

We've included these instructions in the intro text for the form, and so they are now redundant.

### PR DESCRIPTION
**Pull request by Tanuj22**
Fixes #244 

Made two tabs containing the feedback and bug report from respectively.
ezgif-7-0edef031bcbb

---

Developer Certificate of Origin Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors. 1 Letterman Drive Suite D4700 San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

### CODE REVIEW

**Comment by Tanuj22** [comment]
> Looks great so far! One thing I noticed is that we've got two scroll bars for each form (one for the page, one for the embedded form). If possible, I think we should avoid this for the sake of accessibility and UX. Please try to play around with the CSS to scale the iframe's height to the height of the form so we don't have a scroll bar in the iframe :)
> 
> Once this is fixed, I think we should be ready for final review!

Sure!. Will do it soon.

**Comment by Tanuj22** [comment]
@akmadian I was trying to solve it and I found this https://stackoverflow.com/questions/19009849/auto-height-for-iframe-containing-embedded-published-google-doc .It looks like it is not possible to change the height according to the height of the google doc because of `cross domain policy` we can't access the `iframe` child document and therefore ascertain its height in order to resize the `iframe`. One solution is to fix the height to the google doc but then the scrooling would still be present in mobile devices I guess.

**Comment by akmadian** [comment]
Gotcha, looks like there's no good way of going about it then. Unless Breno has any better ideas, I think we're good! Thanks for working on this :)

**Comment by Tanuj22** [comment]
@akmadian Fixed.

**Comment by brenoferreira** [comment]
We've added a Tab component in Vocabulary that should be used. You can see an example of how it's used here https://github.com/creativecommons/cccatalog-frontend/blob/develop/src/components/PhotoDetails.vue#L14

**Comment by Tanuj22** [comment]
@brenoferreira Using only Vocabulary tabs I get this.
Screenshot from 2020-03-28 03-43-32

This is for mobile - 
Screenshot from 2020-03-28 03-44-13
The tabs do not fit. I noticed the same problem exists in https://ccsearch-dev.creativecommons.org/photos/0e0aecc8-3563-4608-b6c5-af49042cf150
Is there a way to fix this?

**Comment by brenoferreira** [comment]
The users can scroll through the tabs. I think that's fine for now. We might come up with a better design soon

**Pull request merged**
