### PR TITLE
Updated Facebooks sharer.php link

### LINKED ISSUE #519: Bug: Facebook Social Sharing Text Doesn't Properly Populate.
**Describe the bug**
When sharing an image on Facebook, the sharer text doesn't properly populate, defaulting to the `<meta name="og:description">` tag text because the Facebook sharer.php no longer accepts inputs. Facebook now generates images, titles, and descriptions for social sharing based on the meta tags. 

**To Reproduce**
1. Go to [https://search.creativecommons.org](https://search.creativecommons.org).
2. Enter something into the search bar and press enter.
3. Click on an image in the search results.
4. Click the `share` button below the image.
5. Click the Facebook avatar to share to Facebook.
6. A new tab will open but the description for the shared image is `Empowering the world...` instead of the correct wording listed above.

**Expected behavior**
When clicking the Facebook sharing link, the description for the shared image should be in the following format:

> "I found an image through CC Search @creativecommons: https://www.flickr.com/photos/biodivlibrary/9240505252" 

**Screenshots**
Screen Shot 2019-10-18 at 5 00 35 PM

**Desktop:**
 - OS: MacOS 10.15
 - Browser: Chrome
 - Version: 77.0.3865.120 (64-bit)

**Additional context**
First brought up by @janeatcc in Issue https://github.com/creativecommons/cccatalog-frontend/issues/271

### PR DESCRIPTION
**Pull request by DantrazTrev**
Fixes #519

There is a custom description added to accommodate all the changes than changing metadata 

Developer Certificate of Origin Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors. 1 Letterman Drive Suite D4700 San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

### CODE REVIEW

**Comment by akmadian** [comment]
I am closing this pull request because you were not approved for work on #519. Please wait for mentor or admin approval before starting work on an issue. 

Assuming that there has been no progress made on #519 by Alucard17 in the next three days (one week from assignment), we could re-open this PR for review.

**Comment by DantrazTrev** [comment]
Hey @akmadian it's been 3 days , and
 as you instructed I'm reopening this PR

**Comment by kgodey** [comment]
go ahead @DantrazTrev

**Comment by akmadian** [comment]
My apologies for not noticing this earlier @DantrazTrev, and thanks Kriti for catching this :)

**Pull request closed without merging**
