### PR TITLE
Modified 'alt' for license names

### LINKED ISSUE #698: Hover Option should be provided to the license Icons to get better user experience.
## Describe the bug
Hover option is not there, when we hover over the license icons! 

## To Reproduce

1. Go to https://search.creativecommons.org/
2. Search any Image

## Expected behavior

Hover Option should be provided to the license Icons to get better user experience.

## Screenshots

e1

## Desktop (please complete the following information)
 - OS: Ubutu
 - Browser Firefox

## Additional context

If this issue is considered, then I would like to work on it :)

### PR DESCRIPTION
**Pull request by abhisheknaiidu**
Fixes #698 

h

---

Developer Certificate of Origin Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors. 1 Letterman Drive Suite D4700 San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

### CODE REVIEW

**Comment by abhisheknaiidu** [comment]
@akmadian While changing, I found that v-for and v-if are present on the same line, I guess this will create problem then, because Vue.js prioritizes the v-for directive over the v-if directive. So under the hood, it loops through every element and then checks the v-if conditional. Should I change it and commit again  ?

**Comment by hemanth-hk** [comment]
`PR` #658 changes that and adds a template tag around

Just a small query, In the image above, I can't see the license icons

**Comment by abhisheknaiidu** [comment]
@hemanth-hk actually I intentionally removed those icons for a moment, so that I can see the alt function behaviour for that particular image. Now I think u got my point!

**Comment by abhisheknaiidu** [comment]
@akmadian Could you once review this :)

**Pull request merged**
