### PR TITLE
Auto focus search bar

### LINKED ISSUE #1032: Auto focus search bar
## Problem

The search bar does not get auto focused when the page loads, also, most webpages with a search have a quick focus option on clicking `/`

## Description

We will have to enable auto-focus on the search when the page loads, it will have to be audited that on which pages we need it to auto-focus(for eg. it is necessary for the homepage but maybe not in the search-guide page), whereas the quick focus should be enabled in all the pages

## Implementation

- [ ] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by abhisheknaiidu**
## Fixes 

Fixes #1032 by @AyanChoudhary 

## Description
Added autofocus to search bar's

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by abhisheknaiidu** [comment]
@zackkrida don't you think, autofocus seems to be an issue for accessibility?
Ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefautofocus

**Comment by zackkrida** [comment]
@abhisheknaiidu I think it's appropriate on a search engine style page like the cc search homepage. All of the search engines do it. From MDN:

> While a screen reader will announce the label of the form control receiving focus, the screen reader will not announce anything before the label

In our case we're only having the user skip our navigation items, so I think it will improve their experience.

This is mainly an a11y issue when a site autofocus an input in a random form on a long content-heavy page.

**Comment by abhisheknaiidu** [comment]
@zackkrida ohk, I got it now 😄

**Comment by abhisheknaiidu** [comment]
@zackkrida Is it fine? or required any changes?

**Comment by zackkrida** [comment]
> I think this is great but that we need to add a label to the input first. I am fine with doing this now as opposed to waiting for a more formal site-wide ARIA cleanup.
> 
> The following should be sufficient, placed right before the input:
> 
> `<label for="searchTerm" class="is-sr-only">Search</label>`

@abhisheknaiidu I think it still needs this label

**Comment by abhisheknaiidu** [comment]
@zackkrida , I've added labels, lemme know if it's fine or not 😁

**Comment by zackkrida** [comment]
Thanks!

**Pull request merged**
