### PR TITLE
fix: Added '<h1>' tags in headings

### LINKED ISSUE #1069: Pages lack `<h1>` tags
**Note: This is currently blocked by https://github.com/creativecommons/vocabulary/issues/529**.

The vast majority of our pages do not use `<h1>`tags for the primary title. This is terrible for a11y and also SEO.

- Homepage ("Search for content to reuse" is `<h2>`): https://search.creativecommons.org/
- Single Result (Image name is `<h5>`): https://search.creativecommons.org/photos/0cdd50d3-e8ca-41a6-ab8e-c71f48dc8807
- About (`<h2>`): https://search.creativecommons.org/about
- Search Syntax (`<h2>`): https://search.creativecommons.org/search-help

In fact, there are only 2 h1 tags in the entire codebase 😿 

Screen Shot 2020-07-21 at 8 56 06 AM

### PR DESCRIPTION
**Pull request by chetas411**
## Fixes

Fixes #[issue number] by @[issue author]
Fixes #1069 by @zackkrida 
## Description

Changes all invalid 'h2/h5' headings to desired 'h1' headings
## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
Hi @chetas411, thank you for your PR, but please re-read the issue: https://github.com/creativecommons/cccatalog-frontend/issues/1069

Your PR will alter the design by changing the styling of the headings. We need to wait until we have new `.title .is-1` classes so that heading style is separate from the actual tag being used.

**Comment by zackkrida** [comment]
@chetas411 No worries! Thanks for looking into the issue. I can show you next steps when it is ready 😸

**Comment by chetas411** [comment]
> @chetas411 No worries! Thanks for looking into the issue. I can show you next steps when it is ready 😸

Looking forward to it!

**Comment by chetas411** [comment]
> hi @chetas411 i put some notes on what will need to be done here: [#1069 (comment)](https://github.com/creativecommons/cccatalog-frontend/issues/1069#issuecomment-668789443)

sure I am closing this PR and would create a new PR with updated code

**Pull request closed without merging**
