### PR TITLE
Create workflow using GitHub Actions to setup CI

### LINKED ISSUE #484: Evaluate Github Actions CI
Set up [Github Actions](https://github.com/features/actions) for our CI use and try it for CD as well.

For CI, it's probably simple as we need only automate:

* build
* tests
* linting

`npm install`, `npm run build`, `npm run test` and `npm run lint` are the commands you would need for that.

If possible, during build of PRs it would be interesting to see if the GH Actions supports moving the associated issue to the `In Progress` column of the [Active Sprint project](https://github.com/orgs/creativecommons/projects/7).

### PR DESCRIPTION
**Pull request by SaurabhAgarwala**
## Fixes

Partially fixes #484 by @brenoferreira

## Description

This PR creates a new workflow using GitHub Actions for setting up CI

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by SaurabhAgarwala** [comment]
@brenoferreira I have added the unit tests to the CI workflow as well. Please review it

**Comment by SaurabhAgarwala** [comment]
@kgodey The logic behind separating the build, lint and tests into three separate jobs is that these three jobs can then run in parallel as specified under the [jobs section here](https://help.github.com/en/actions/getting-started-with-github-actions/core-concepts-for-github-actions#job). However, I just analyzed that running these three steps within the same job sequentially will cause each workflow run to just take around 5 seconds extra, which I don't think is a significant time and so we can move this to run sequentially as suggested by you.
Either way has some trade-off. Please let me know which approach to finally take and I will accordingly make the necessary changes.

**Comment by kgodey** [comment]
I'll defer to @brenoferreira on the best approach.

**Comment by brenoferreira** [comment]
I'll have to look into the GH Actions docs to review this more properly, but I think it's fine to run some tasks sequentially. Specially tasks that are dependencies of other tasks, such as `install` can run first and then the others can run afterwards

**Comment by SaurabhAgarwala** [comment]
Sure, I will update the PR to make it run sequentially.

**Comment by SaurabhAgarwala** [comment]
@brenoferreira I have made the instructed changes. Please review it.

**Comment by SaurabhAgarwala** [comment]
@brenoferreira Any updates on this PR?

**Pull request merged**
